myblog/views/auth.py
import functools
from os import error
from flask import(
    render_template, Blueprint, flash, g, redirect, request, session, url_for
)

from werkzeug.security import check_password_hash, generate_password_hash
from flaskext.mysql import MySQL
from myblog.models.user import User

from myblog import db



auth = Blueprint('auth', __name__, url_prefix='/auth')

#Registrar un usuario 
@auth.route('/register', methods=('GET','POST'))
def register():
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
        tipoUsuario="usuario"
        
        #instruccion sql
        user = User(username, generate_password_hash(password),tipoUsuario)

        error = None
        if not username:
            error = 'Se requiere nombre de usuario'
        elif not password:
            error = 'Se requiere contraseña'
        
        user_name = User.query.filter_by(username = username).first()
        if user_name == None:
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('auth.login'))
        else:
            error = f'El usuario {username} ya esta registrado'
        flash(error)
        
    return render_template('auth/register.html')



@auth.route('/registerAdmin', methods=('GET','POST'))
def registerAdmin():
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
        tipoUsuario=request.form.get('select')
        
        #instruccion sql
        user = User(username, generate_password_hash(password),tipoUsuario)

        error = None
        if not username:
            error = 'Se requiere nombre de usuario'
        elif not password:
            error = 'Se requiere contraseña'
        
        user_name = User.query.filter_by(username = username).first()
        if user_name == None:
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('blog.indexAdmin'))
        else:
            error = f'El usuario {username} ya esta registrado'
        flash(error)
        
    return render_template('auth/registerAdmin.html')

@auth.route('/sobre')
def sobre():
    return render_template('blog/sobre.html')

@auth.route('mostrarUsuarios')
def mostrarUsuarios():
    data = User.query.all()
    db.session.commit()
    return render_template('blog/panelAdmin.html',data=data)



@auth.route('/login', methods=('GET','POST'))
def login():
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
        tipoUsuario=request.form.get('select')

        error = None
        
        user = User.query.filter_by(username = username).first()
        
        if user == None:
            error = 'Nombre de usuario incorrecto'
        if not check_password_hash(user.password, password):
            error = 'Contraseña incorrecta'
            #validacion de tipo de usuario
        if not  user.tipoUsuario==tipoUsuario:
            error='Tipo de eusuario incorrecto'
        
        if not user.tipoUsuario=="Administrador":
            session.clear()
            session['user_id'] = user.id
            return redirect(url_for('blog.indexAdmin'))
            #return render_template('blog/indexAdmin.html')
        
        elif error is None:
            session.clear()
            session['user_id'] = user.id
            
            return redirect(url_for('blog.index'))
        
        flash(error)
        
        
    return render_template('auth/login.html')


@auth.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')

    if user_id is None:
        g.user = None
    else:
        g.user = User.query.get_or_404(user_id)

@auth.route('/logout')
def logout():
    session.clear()
    return redirect(url_for('blog.index'))

def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            return redirect(url_for('auth.login'))
        return view(**kwargs)
    return wrapped_view



@auth.route('/delete/<int:id>')
def delete(id):
     user=User.query.get(id)
     db.session.delete(user)
     db.session.commit() 
     return redirect(url_for('blog.indexAdmin'))

myblog/views/blog.py
from operator import pos
from flask import(
    render_template, Blueprint, flash, g, redirect, request, url_for
)

from werkzeug.exceptions import abort

from myblog.models.post import Post
from myblog.models.user import User

from myblog.views.auth import login_required

from myblog import db

blog = Blueprint('blog', __name__)

#Obtner un ususario
def get_user(id):
    user = User.query.get_or_404(id)
    return user

@blog.route("/")
def index():
    posts = Post.query.all()
    posts = list(reversed(posts))
    db.session.commit()
    return render_template('blog/index.html', posts = posts, get_user=get_user)

@blog.route("/IndexAdmin")
def indexAdmin():
    posts = Post.query.all()
    posts = list(reversed(posts))
    db.session.commit()
    return render_template('blog/indexAdmin.html', posts = posts, get_user=get_user)

#Registrar un post 
@blog.route('/blog/create', methods=('GET','POST'))
@login_required
def create():
    if request.method == 'POST':
        title = request.form.get('title')
        body = request.form.get('body')

        post = Post(g.user.id, title, body)

        error = None
        if not title:
            error = 'Se requiere un título'
        
        if error is not None:
            flash(error)
        else:
            db.session.add(post)
            db.session.commit()
            return redirect(url_for('blog.index'))
        
        flash(error)
        
    return render_template('blog/create.html')

@blog.route('/blog/createAdmin', methods=('GET','POST'))
@login_required
def createAdmin():
    if request.method == 'POST':
        title = request.form.get('title')
        body = request.form.get('body')

        post = Post(g.user.id, title, body)

        error = None
        if not title:
            error = 'Se requiere un título'
        
        if error is not None:
            flash(error)
        else:
            db.session.add(post)
            db.session.commit()
            #return render_template('blog/indexAdmin.html')
            return redirect(url_for('blog.indexAdmin'))
        
        flash(error)
        
    return render_template('blog/createAdmin.html')

def get_post(id, check_author=True):
    post = Post.query.get(id)

    if post is None:
        abort(404, f'Id {id} de la publicación no existe.')

    if check_author and post.author != g.user.id:
        abort(404)
    
    return post

#Update post 
@blog.route('/blog/update/<int:id>', methods=('GET','POST'))
@login_required
def update(id):

    post = get_post(id) 

    if request.method == 'POST':
        post.title = request.form.get('title')
        post.body = request.form.get('body')

        error = None
        if not post.title:
            error = 'Se requiere un título'
        
        if error is not None:
            flash(error)
        else:
            db.session.add(post)
            db.session.commit()
            return redirect(url_for('blog.index'))
        
        flash(error)
        
    return render_template('blog/update.html', post=post)

@blog.route('/blog/updateAdmin/<int:id>', methods=('GET','POST'))
@login_required
def updateAdmin(id):

    post = get_post(id) 

    if request.method == 'POST':
        post.title = request.form.get('title')
        post.body = request.form.get('body')

        error = None
        if not post.title:
            error = 'Se requiere un título'
        
        if error is not None:
            flash(error)
        else:
            db.session.add(post)
            db.session.commit()
            return redirect(url_for('blog.indexAdmin'))
        
        flash(error)
        
    return render_template('blog/updateAdmin.html', post=post)



#Eliminar un post
@blog.route('/blog/delete/<int:id>')
@login_required
def delete(id):
    
    post = get_post(id)
    db.session.delete(post)
    db.session.commit()

    return redirect(url_for('blog.index'))

@blog.route('/blog/deleteAdmin/<int:id>')
@login_required
def deleteAdmin(id):
    
    post = get_post(id)
    db.session.delete(post)
    db.session.commit()

    return redirect(url_for('blog.indexAdmin'))

@blog.route('/mostrarPublicaciones')
def mostrarPublicaciones():
    data = Post.query.all()
    db.session.commit()
    return render_template('blog/mostrarPublicaciones.html',data=data)

myblog/templates/blog/create.html
{% extends 'base.html' %}
{% block header %}
    <h2>{% block title %}Crear una publicación {% endblock %}</h2>
{% endblock %}

{% block content %}
    <form method="POST">
        <label for="title">Título</label>
        <input type="text" name="title" id="title" required>
        <label for="body">Contenido</label>
        <textarea name="body" id="body" cols="30" rows="10"></textarea>
        <input type="submit", value="Guardar">
    </form>
{% endblock %}

myblog/templates/blog/createAdmin.html
{% extends 'baseAdmin.html' %}
{% block header %}
    <h2>{% block title %}Crear una publicación {% endblock %}</h2>
{% endblock %}

{% block content %}
    <form method="POST">
        <label for="title">Título</label>
        <input type="text" name="title" id="title" required>
        <label for="body">Contenido</label>
        <textarea name="body" id="body" cols="30" rows="10"></textarea>
        <input type="submit", value="Guardar">
    </form>
{% endblock %}

myblog/templates/blog/index.html
{% extends 'base.html' %}
{% block header %}
    <h2>{% block title %}Publicaciones {% endblock %}</h2>
    {% if g.user %}
        <a href="{{ url_for('blog.create') }}">Nueva Publicación</a>
    {% endif%}
{% endblock %}

{% block content %}

{% for post in posts %}
    <article>
        <header>
            <div>
               <h1>{{ post.title }}</h1>
                <div class="about">
                    Publicado por {{ get_user(post.author).username}}
                    el {{ post.created.strftime('%Y-%m-%d') }}
                </div> 
            </div>
            <div>
                {% if g.user.id == post.author %}
                    <a href="{{ url_for('blog.update', id=post.id) }}">Editar</a>
                    <a href="{{ url_for('blog.delete', id=post.id) }}">Eliminar</a>
                {% endif %}
            </div>
        </header>
        <div>
            <p>{{ post.body }}</p>
        </div>
    </article>
{% endfor %}

{% endblock %}

myblog/templates/blog/indexAdmin.html
{% extends 'baseAdmin.html' %}
{% block header %}
    <h2>{% block title %}Publicaciones {% endblock %}</h2>
    {% if g.user %}
        <a href="{{ url_for('blog.createAdmin') }}">Nueva Publicación</a>
    {% endif%}
{% endblock %}

{% block content %}

{% for post in posts %}
    <article>
        <header>
            <div>
               <h1>{{ post.title }}</h1>
                <div class="about">
                    Publicado por {{ get_user(post.author).username}}
                    el {{ post.created.strftime('%Y-%m-%d') }}
                </div> 
            </div>
            <div>
                {% if g.user.id == post.author %}
                    <a href="{{ url_for('blog.updateAdmin', id=post.id) }}">Editar</a>
                    <a href="{{ url_for('blog.deleteAdmin', id=post.id) }}">Eliminar</a>
                {% endif %}
            </div>
        </header>
        <div>
            <p>{{ post.body }}</p>
        </div>
    </article>
{% endfor %}

{% endblock %}

myblog/templates/blog/mostrarPublicaciones.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{{ url_for('static', filename='img/blog.ico')}}" type="image/x-icon">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    
    <title>{% block title %}{% endblock %}-Myblog</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css')}}">
</head>
<body>
    <header class="header">
        <div class="nav">
                <div>
                <a href="{{ url_for('blog.indexAdmin') }}">
                <h1>MyBlog</h1>  
                </a>
            </div>
            <nav>
                {% if g.user %}
                <img src="{{ url_for('static', filename='img/user.png')}}" alt="">
                <span>{{ g.user.username }}</span>
                <a href="{{ url_for('auth.logout') }}">Cerrar Sesión</a>
                <a href="{{ url_for('auth.mostrarUsuarios') }}">Mostrar Usuarios</a>
                <a href="{{ url_for('auth.registerAdmin') }}">Registrar Usuario</a>
                <a href="{{ url_for('blog.mostrarPublicaciones') }}">Registro de publicaciones</a>
                <a href="{{ url_for('auth.sobre') }}">sobre nosotros</a>
                
                {% endif %}
            </nav>
        </div>
        
    </header>

    <section>
        <div class="content">
            <header>{% block header %}{% endblock %}</header>

            {% for message in get_flashed_messages() %}
            <div class="flash"> {{ message }}</div>
            {% endfor %}

            {% block content %}{% endblock %}
        </div>
        
    </section>
    <div>
        <table class="table table-light">
            <thead class="thead-light">
                <tr>
                    <th>id</th>
                    <th>Autor</th>
                    <th>Titulo</th>
                    <th>Cuerpo del Post</th>
                    <th>Fecha del Post</th>
                    
                </tr>
            </thead>
            <tbody>
                {% for data  in data %}
                <tr>
                    <td>{{data.id}}</td>
                    <td>{{data.author}}</td>
                    <td>{{data.title}}</td>
                    <td>{{data.body}}</td>
                    <td>{{data.created}}</td>
                    
                </tr>
                {% endfor %}
    </div>
   



</body>
</html>

myblog/templates/blog/panelAdmin.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{{ url_for('static', filename='img/blog.ico')}}" type="image/x-icon">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    
    <title>{% block title %}{% endblock %}-Myblog</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css')}}">
</head>
<body>
    <header class="header">
        <div class="nav">
                <div>
                <a href="{{ url_for('blog.indexAdmin') }}">
                <h1>MyBlog</h1>  
                </a>
            </div>
            <nav>
                {% if g.user %}
                <img src="{{ url_for('static', filename='img/user.png')}}" alt="">
                <span>{{ g.user.username }}</span>
                <a href="{{ url_for('auth.logout') }}">Cerrar Sesión</a>
                <a href="{{ url_for('auth.mostrarUsuarios') }}">Mostrar Usuarios</a>
                <a href="{{ url_for('auth.registerAdmin') }}">Registrar Usuario</a>
                
                
                <a href="{{ url_for('auth.sobre') }}">sobre nosotros</a>
                
                {% endif %}
            </nav>
        </div>
        
    </header>

    <section>
        <div class="content">
            <header>{% block header %}{% endblock %}</header>

            {% for message in get_flashed_messages() %}
            <div class="flash"> {{ message }}</div>
            {% endfor %}

            {% block content %}{% endblock %}
        </div>
        
    </section>
    <div>
        <table class="table table-light">
            <thead class="thead-light">
                <tr>
                    <th>id</th>
                    <th>Nombre de Usuario</th>
                    <th>Tipo de Usuario</th>
                    <th>Acciones</th>
                    
                </tr>
            </thead>
            <tbody>
                {% for data  in data %}
                <tr>
                    <td>{{data.id}}</td>
                    <td>{{data.username}}</td>
                    <td>{{data.tipoUsuario}}</td>
                    <td>
                        <a class="btn btn-danger" href="{{ url_for('auth.delete', id=data.id) }}">Eliminar</a>
                    </td>
                </tr>
                {% endfor %}
    </div>
   



</body>
</html>


 

myblog/templates/blog/sobre.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{{ url_for('static', filename='img/blog.ico')}}" type="image/x-icon">
    
    <title>{% block title %}{% endblock %}-Myblog</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css')}}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles2.css')}}">
</head>
<body>
    <header class="header">
        <div class="nav">
                <div>
                <a href="{{ url_for('blog.index') }}">
                <h1>MyBlog</h1>  
                </a>
            </div>
            
        </div>
        
    </header>

    <section>
        <div class="content">
            <header>{% block header %}{% endblock %}</header>

            {% for message in get_flashed_messages() %}
            <div class="flash"> {{ message }}</div>
            {% endfor %}

            {% block content %}{% endblock %}
        </div>
        
    </section>
    <div class="container__background-triangle">
        <div class="triangle triangle1"></div>
        <div class="triangle triangle2"></div>
        <div class="triangle triangle3"></div>
    </div>

    <div class="container__cards">
        <div class="card">
            <div class="cover__card">
                <img src="{{ url_for('static', filename='img/img-1.jpg')}}" alt="">
            </div>
            <h2>Blog Web</h2>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Qui sunt eius dolore pariatur. Error, provident et similique sunt voluptate odit eos facere expedita, culpa at officia magnam quia vel eius!</p>
            <hr>
            <div class="footer__card">
                <h3 class="user__name">lorem</h3>
                <i>08 Marzo</i>
            </div>
        </div>
        <div class="card">
            <div class="cover__card">
                <img src="{{ url_for('static', filename='img/img-3.jpg')}}" alt="">
            </div>
            <h2>Laboratorio de programacion web</h2>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Qui sunt eius dolore pariatur. Error, provident et similique sunt voluptate odit eos facere expedita, culpa at officia magnam quia vel eius!</p>
            <hr>
            <div class="footer__card">
                <h3 class="user__name">Valeria Campos</h3>
                <i>08 Marzo</i>
            </div>
        </div>
        <div class="card">
            <div class="cover__card">
                <img src="{{ url_for('static', filename='img/img-2.jpg')}}" alt="">
            </div>
            <h2>PIA</h2>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Qui sunt eius dolore pariatur. Error, provident et similique sunt voluptate odit eos facere expedita, culpa at officia magnam quia vel eius!</p>
            <hr>
            <div class="footer__card">
                <h3 class="user__name">Manuel Flores</h3>
                <i>08 Marzo</i>
            </div>
        </div>
    </div>

   



</body>
</html>

myblog/templates/blog/update.html
{% extends 'base.html' %}
{% block header %}
    <h2>{% block title %}Actualizar una publicación {% endblock %}</h2>
{% endblock %}

{% block content %}
    <form method="POST">
        <label for="title">Título</label>
        <input type="text" name="title" id="title" value="{{ post.title }}" required>
        <label for="body">Contenido</label>
        <textarea name="body" id="body" cols="30" rows="10">{{ post.body }}</textarea>
        <input type="submit", value="Guardar">
    </form>
{% endblock %}

myblog/templates/blog/updateAdmin.html
{% extends 'baseAdmin.html' %}
{% block header %}
    <h2>{% block title %}Actualizar una publicación {% endblock %}</h2>
{% endblock %}

{% block content %}
    <form method="POST">
        <label for="title">Título</label>
        <input type="text" name="title" id="title" value="{{ post.title }}" required>
        <label for="body">Contenido</label>
        <textarea name="body" id="body" cols="30" rows="10">{{ post.body }}</textarea>
        <input type="submit", value="Guardar">
    </form>
{% endblock %}