myblog/views/auth.py
import functools
from os import error
from flask import(
    render_template, Blueprint, flash, g, redirect, request, session, url_for
)

from werkzeug.security import check_password_hash, generate_password_hash
from flaskext.mysql import MySQL
from myblog.models.user import User

from myblog import db



auth = Blueprint('auth', __name__, url_prefix='/auth')

#Registrar un usuario 
@auth.route('/register', methods=('GET','POST'))
def register():
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
        tipoUsuario="usuario"
        
        #instruccion sql
        user = User(username, generate_password_hash(password),tipoUsuario)

        error = None
        if not username:
            error = 'Se requiere nombre de usuario'
        elif not password:
            error = 'Se requiere contraseña'
        
        user_name = User.query.filter_by(username = username).first()
        if user_name == None:
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('auth.login'))
        else:
            error = f'El usuario {username} ya esta registrado'
        flash(error)
        
    return render_template('auth/register.html')



@auth.route('/registerAdmin', methods=('GET','POST'))
def registerAdmin():
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
        tipoUsuario=request.form.get('select')
        
        #instruccion sql
        user = User(username, generate_password_hash(password),tipoUsuario)

        error = None
        if not username:
            error = 'Se requiere nombre de usuario'
        elif not password:
            error = 'Se requiere contraseña'
        
        user_name = User.query.filter_by(username = username).first()
        if user_name == None:
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('blog.indexAdmin'))
        else:
            error = f'El usuario {username} ya esta registrado'
        flash(error)
        
    return render_template('auth/registerAdmin.html')

@auth.route('/sobre')
def sobre():
    return render_template('blog/sobre.html')

@auth.route('mostrarUsuarios')
def mostrarUsuarios():
    data = User.query.all()
    db.session.commit()
    return render_template('blog/panelAdmin.html',data=data)



@auth.route('/login', methods=('GET','POST'))
def login():
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
        tipoUsuario=request.form.get('select')

        error = None
        
        user = User.query.filter_by(username = username).first()
        
        if user == None:
            error = 'Nombre de usuario incorrecto'
        if not check_password_hash(user.password, password):
            error = 'Contraseña incorrecta'
            #validacion de tipo de usuario
        if not  user.tipoUsuario==tipoUsuario:
            error='Tipo de eusuario incorrecto'
        
        if not user.tipoUsuario=="Administrador":
            session.clear()
            session['user_id'] = user.id
            return redirect(url_for('blog.indexAdmin'))
            #return render_template('blog/indexAdmin.html')
        
        elif error is None:
            session.clear()
            session['user_id'] = user.id
            
            return redirect(url_for('blog.index'))
        
        flash(error)
        
        
    return render_template('auth/login.html')


@auth.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')

    if user_id is None:
        g.user = None
    else:
        g.user = User.query.get_or_404(user_id)

@auth.route('/logout')
def logout():
    session.clear()
    return redirect(url_for('blog.index'))

def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            return redirect(url_for('auth.login'))
        return view(**kwargs)
    return wrapped_view



@auth.route('/delete/<int:id>')
def delete(id):
     user=User.query.get(id)
     db.session.delete(user)
     db.session.commit() 
     return redirect(url_for('blog.indexAdmin'))

myblog/views/blog.py
from operator import pos
from flask import(
    render_template, Blueprint, flash, g, redirect, request, url_for
)

from werkzeug.exceptions import abort

from myblog.models.post import Post
from myblog.models.user import User

from myblog.views.auth import login_required

from myblog import db

blog = Blueprint('blog', __name__)

#Obtner un ususario
def get_user(id):
    user = User.query.get_or_404(id)
    return user

@blog.route("/")
def index():
    posts = Post.query.all()
    posts = list(reversed(posts))
    db.session.commit()
    return render_template('blog/index.html', posts = posts, get_user=get_user)

@blog.route("/IndexAdmin")
def indexAdmin():
    posts = Post.query.all()
    posts = list(reversed(posts))
    db.session.commit()
    return render_template('blog/indexAdmin.html', posts = posts, get_user=get_user)

#Registrar un post 
@blog.route('/blog/create', methods=('GET','POST'))
@login_required
def create():
    if request.method == 'POST':
        title = request.form.get('title')
        body = request.form.get('body')

        post = Post(g.user.id, title, body)

        error = None
        if not title:
            error = 'Se requiere un título'
        
        if error is not None:
            flash(error)
        else:
            db.session.add(post)
            db.session.commit()
            return redirect(url_for('blog.index'))
        
        flash(error)
        
    return render_template('blog/create.html')

@blog.route('/blog/createAdmin', methods=('GET','POST'))
@login_required
def createAdmin():
    if request.method == 'POST':
        title = request.form.get('title')
        body = request.form.get('body')

        post = Post(g.user.id, title, body)

        error = None
        if not title:
            error = 'Se requiere un título'
        
        if error is not None:
            flash(error)
        else:
            db.session.add(post)
            db.session.commit()
            #return render_template('blog/indexAdmin.html')
            return redirect(url_for('blog.indexAdmin'))
        
        flash(error)
        
    return render_template('blog/createAdmin.html')

def get_post(id, check_author=True):
    post = Post.query.get(id)

    if post is None:
        abort(404, f'Id {id} de la publicación no existe.')

    if check_author and post.author != g.user.id:
        abort(404)
    
    return post

#Update post 
@blog.route('/blog/update/<int:id>', methods=('GET','POST'))
@login_required
def update(id):

    post = get_post(id) 

    if request.method == 'POST':
        post.title = request.form.get('title')
        post.body = request.form.get('body')

        error = None
        if not post.title:
            error = 'Se requiere un título'
        
        if error is not None:
            flash(error)
        else:
            db.session.add(post)
            db.session.commit()
            return redirect(url_for('blog.index'))
        
        flash(error)
        
    return render_template('blog/update.html', post=post)

@blog.route('/blog/updateAdmin/<int:id>', methods=('GET','POST'))
@login_required
def updateAdmin(id):

    post = get_post(id) 

    if request.method == 'POST':
        post.title = request.form.get('title')
        post.body = request.form.get('body')

        error = None
        if not post.title:
            error = 'Se requiere un título'
        
        if error is not None:
            flash(error)
        else:
            db.session.add(post)
            db.session.commit()
            return redirect(url_for('blog.indexAdmin'))
        
        flash(error)
        
    return render_template('blog/updateAdmin.html', post=post)



#Eliminar un post
@blog.route('/blog/delete/<int:id>')
@login_required
def delete(id):
    
    post = get_post(id)
    db.session.delete(post)
    db.session.commit()

    return redirect(url_for('blog.index'))

@blog.route('/blog/deleteAdmin/<int:id>')
@login_required
def deleteAdmin(id):
    
    post = get_post(id)
    db.session.delete(post)
    db.session.commit()

    return redirect(url_for('blog.indexAdmin'))

@blog.route('/mostrarPublicaciones')
def mostrarPublicaciones():
    data = Post.query.all()
    db.session.commit()
    return render_template('blog/mostrarPublicaciones.html',data=data)

myblog/templates/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{{ url_for('static', filename='img/blog.ico')}}" type="image/x-icon">
    
    <title>{% block title %}{% endblock %}-Myblog</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css')}}">
</head>
<body>
    <header class="header">
        <div class="nav">
                <div>
                <a href="{{ url_for('blog.index') }}">
                <h1>MyBlog</h1>  
                </a>
            </div>
            <nav>
                {% if g.user %}
                <img src="{{ url_for('static', filename='img/user.png')}}" alt="">
                <span>{{ g.user.username }}</span>
                <a href="{{ url_for('auth.logout') }}">Cerrar Sesión</a>
                {% else %}
                <a href="{{ url_for('auth.register') }}">Registrar Usuario</a>
                <a href="{{ url_for('auth.login') }}">Iniciar Sesión</a>
                
                <a href="{{ url_for('auth.sobre') }}">sobre nosotros</a>
                {% endif %}
                
            </nav>
           
        </div>
        
    </header>

    <section>
        <div class="content">
            <header>{% block header %}{% endblock %}</header>

            {% for message in get_flashed_messages() %}
            <div class="flash"> {{ message }}</div>
            {% endfor %}

            {% block content %}{% endblock %}
        </div>
        
    </section>
</body>
</html>

myblog/templates/baseAdmin.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{{ url_for('static', filename='img/blog.ico')}}" type="image/x-icon">
    
    <title>{% block title %}{% endblock %}-Myblog</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css')}}">
</head>
<body>
    <header class="header">
        <div class="nav">
                <div>
                <a href="{{ url_for('blog.indexAdmin') }}">
                <h1>MyBlog</h1>  
                </a>
            </div>
            <nav>
                {% if g.user %}
                <img src="{{ url_for('static', filename='img/user.png')}}" alt="">
                <span>{{ g.user.username }}</span>
                <a href="{{ url_for('auth.logout') }}">Cerrar Sesión</a>
                <a href="{{ url_for('auth.mostrarUsuarios') }}">Mostrar Usuarios</a>
                <a href="{{ url_for('blog.mostrarPublicaciones') }}">Registro de publicaciones</a>
                <a href="{{ url_for('auth.registerAdmin') }}">Registrar Usuario</a>
                <a href="{{ url_for('auth.sobre') }}">sobre nosotros</a>
                {% endif %}
                
            </nav>
           
        </div>
        
    </header>

    <section>
        <div class="content">
            <header>{% block header %}{% endblock %}</header>

            {% for message in get_flashed_messages() %}
            <div class="flash"> {{ message }}</div>
            {% endfor %}

            {% block content %}{% endblock %}
        </div>
        
    </section>
</body>
</html>